### ISSUE TITLE
Installation instructions incorrect

### ISSUE THREAD

**Issue by dmathisen** [IWANABETHATGUY/rspack-plugin-dotenv#1]
The installation and setup instructions seem wrong. I had to do a lot of trial and error to get this working.

First, under "Installation", I'm fairly sure there should be instructions for `npm install rspack-plugin-dotenv --save-dev`.

Next, under "Usage", it should be `const Dotenv = require('rspack-plugin-dotenv');` (not `dotenv-webpack`... using that threw a ton of errors)

Note: the project I'm working on was a custom React project built from the ground up (not using create-react-app) and I'm converting it from webpack to rspack.

Note 2: I'm happy to submit a PR to fix the readme docs, but wanted to post here to confirm that the above is correct first.

**Comment by IWANABETHATGUY** [comment]
Yeah, you are right. The package name is `rspack-plugin-dotenv`
Sorry for the misleading description in README. 
I am very glad that you could open a pr to resolve this.

**Comment by dmathisen** [comment]
@IWANABETHATGUY PR created here.
https://github.com/IWANABETHATGUY/rspack-plugin-dotenv/pull/2
